#ifndef VESC_Status_11_Consts_h_
#define VESC_Status_11_Consts_h_

typedef enum VESC_Status_11_ErrorCode_Enum
{
	VESC_STATUS_11_ERRORCODE_OK = 0,
	VESC_STATUS_11_ERRORCODE_OVERTEMP = 1,
	VESC_STATUS_11_ERRORCODE_OVERCURRENT = 2,
	VESC_STATUS_11_ERRORCODE_OVERVOLTAGE = 3,
	VESC_STATUS_11_ERRORCODE_UNDERVOLTAGE = 4,
	VESC_STATUS_11_ERRORCODE_ENCODERFAULT = 5,
	VESC_STATUS_11_ERRORCODE_MOSFET_OVERTEMP = 6,
	VESC_STATUS_11_ERRORCODE_STALL = 7,

} VESC_Status_11_ErrorCode;

#endif //VESC_Status_11_Consts_h_