#ifndef VESC_Status_10_Consts_h_
#define VESC_Status_10_Consts_h_

//https://github.com/wisniax/RoverControlApp/wiki#-mqtt-rover-status

#define VESC_STATUS_10_FLAGS_MASK_PADCONNECTED 0b1
#define VESC_STATUS_10_FLAGS_MASK_MOTORCUTOFFBUTTON 0b10

typedef enum VESC_Status_10_CommunicationState_enum
{
	VESC_STATUS_10_COMMUNICATIONSTATE_CREATED = 0,
	VESC_STATUS_10_COMMUNICATIONSTATE_OPENING = 1,
	VESC_STATUS_10_COMMUNICATIONSTATE_OPENED = 2,
	VESC_STATUS_10_COMMUNICATIONSTATE_CLOSING = 3,
	VESC_STATUS_10_COMMUNICATIONSTATE_CLOSED = 4,
	VESC_STATUS_10_COMMUNICATIONSTATE_FAULTED = 5
} VESC_Status_10_CommunicationState;

typedef enum VESC_Status_10_ControlMode_enum
{
	VESC_STATUS_10_CONTROLMODE_ESTOP = 0,
	VESC_STATUS_10_CONTROLMODE_ROVER = 1,
	VESC_STATUS_10_CONTROLMODE_MANIPULATOR = 2,
	VESC_STATUS_10_CONTROLMODE_AUTONOMY = 3
} VESC_Status_10_ControlMode;

//TODO VESC_Status_10_CanBusState_enum

#endif //VESC_Status_10_Consts_h_