#ifndef VESC_Status_10_Consts_h_
#define VESC_Status_10_Consts_h_

//https://github.com/wisniax/RoverControlApp/wiki#-mqtt-rover-status

#define VESC_STATUS_10_CONTROLMODE_MASK_NONE						0
#define VESC_STATUS_10_CONTROLMODE_MASK_ESTOP						(1 << 0)
#define VESC_STATUS_10_CONTROLMODE_MASK_STOP						(1 << 1)
#define VESC_STATUS_10_CONTROLMODE_MASK_CONFIG						(1 << 2)
#define VESC_STATUS_10_CONTROLMODE_MASK_DRIVE						(1 << 3)
#define VESC_STATUS_10_CONTROLMODE_MASK_ROBOTIC_ARM					(1 << 4)
#define VESC_STATUS_10_CONTROLMODE_MASK_DEEP_SAMPLER				(1 << 5)
#define VESC_STATUS_10_CONTROLMODE_MASK_SURFACE_SAMPLER				(1 << 6)
#define VESC_STATUS_10_CONTROLMODE_MASK_DRIVE_AUTONOMY				(1 << 7)
#define VESC_STATUS_10_CONTROLMODE_MASK_ROBOTIC_ARM_AUTONOMY		(1 << 8)
#define VESC_STATUS_10_CONTROLMODE_MASK_DEEP_SAMPLER_AUTONOMY		(1 << 9)
#define VESC_STATUS_10_CONTROLMODE_MASK_SURFACE_SAMPLER_AUTONOMY	(1 << 10)

typedef enum VESC_Status_10_CommunicationState_enum
{
	VESC_STATUS_10_COMMUNICATIONSTATE_CREATED = 0,
	VESC_STATUS_10_COMMUNICATIONSTATE_OPENING = 1,
	VESC_STATUS_10_COMMUNICATIONSTATE_OPENED = 2,
	VESC_STATUS_10_COMMUNICATIONSTATE_CLOSING = 3,
	VESC_STATUS_10_COMMUNICATIONSTATE_CLOSED = 4,
	VESC_STATUS_10_COMMUNICATIONSTATE_FAULTED = 5
} VESC_Status_10_CommunicationState;

#endif //VESC_Status_10_Consts_h_