#ifndef VESC_Status_9_Consts_h_
#define VESC_Status_9_Consts_h_

#define VESC_STATUS_9_STATUS_MASK_HOTSWAP_MASTER 0b1
#define VESC_STATUS_9_STATUS_MASK_HOTSWAP_SLAVE_A 0b10
#define VESC_STATUS_9_STATUS_MASK_HOTSWAP_SLAVE_B 0b100
#define VESC_STATUS_9_STATUS_MASK_HOTSWAP_DRIVE_STOP 0b1000
#define VESC_STATUS_9_STATUS_MASK_HOTSWAP_GPIO_1 0b10000
#define VESC_STATUS_9_STATUS_MASK_HOTSWAP_GPIO_2 0b100000
#define VESC_STATUS_9_STATUS_MASK_HOTSWAP_GPIO_3 0b1000000
#define VESC_STATUS_9_STATUS_MASK_HOTSWAP_GPIO_4 0b10000000

// typedef enum VESC_Status_9_BatteryStatus_enum
// {
// 	/*who knows, who cares*/
// } VESC_Status_9_BatteryStatus;

#endif //VESC_Status_9_Consts_h_